# Editor colors
[editor]
bg = "#282a36"  # Background: dark gray
fg = "#f8f8f2"  # Foreground: off-white
select_bg = "#44475a"  # Selection bg: dark blue-gray
select_fg = "#f8f8f2"  # Selection fg: off-white
inactive_select_bg = "#402725"  # Inactive selection bg: dark brown
caret = "#f8f8f0"  # Caret: off-white
caret_width = 1  # Caret width: 1
border_width = 0  # Border width: 0
focus_border_width = 0  # Focus border width: 0

# General syntax colors
[general]
comment = "#6272a4"  # Comments: blue-gray
error = "#ff3333"  # Errors: bright red
escape = "#f8f8f2"  # Escapes: off-white
keyword = "#ff79c6"  # Keywords: pink
name = "#50fa7b"  # Names: green
string = "#99c794"  # Strings: light green
punctuation = "#ff79c6"  # Punctuation: pink

# Keyword colors
[keyword]
constant = "#bd93f9"  # Constants: light purple
declaration = "#ff79c6"  # Declarations: pink
namespace = "#ff79c6"  # Namespaces: pink
pseudo = "#ff79c6"  # Pseudo keywords: pink
reserved = "#ff79c6"  # Reserved keywords: pink
type = "#ff79c6"  # Types: pink

# Name colors
[name]
attr = "#50fa7b"  # Attributes: green
builtin = "#ffb86c"  # Built-ins: light orange
builtin_pseudo = "#ffb86c"  # Built-in pseudo: light orange
class = "#8be9fd"  # Classes: light blue
class_variable = "#f8f8f2"  # Class variables: off-white
constant = "#bd93f9"  # Constants: light purple
decorator = "#8be9fd"  # Decorators: light blue
entity = "#50fa7b"  # Entities: green
exception = "#8be9fd"  # Exceptions: light blue
function = "#50fa7b"  # Functions: green
global_variable = "#f8f8f2"  # Global variables: off-white
instance_variable = "#f8f8f2"  # Instance variables: off-white
label = "#50fa7b"  # Labels: green
magic_function = "#50fa7b"  # Magic functions: green
magic_variable = "#f8f8f2"  # Magic variables: off-white
namespace = "#f8f8f2"  # Namespace: off-white
tag = "#ff79c6"  # Tags: pink
variable = "#ffb86c"  # Variables: light orange

# Operator colors
[operator]
symbol = "#ff79c6"  # Symbols: pink
word = "#ff79c6"  # Words: pink

# String colors
[string]
affix = "#f1fa8c"  # Affix: yellow
char = "#f1fa8c"  # Char: yellow
delimeter = "#f1fa8c"  # Delimeter: yellow
doc = "#f1fa8c"  # Doc: yellow
double = "#f1fa8c"  # Double: yellow
escape = "#f8f8f2"  # Escape: off-white
heredoc = "#f1fa8c"  # Heredoc: yellow
interpol = "#f1fa8c"  # Interpol: yellow
regex = "#f1fa8c"  # Regex: yellow
single = "#f1fa8c"  # Single: yellow
symbol = "#f1fa8c"  # Symbol: yellow

# Number colors
[number]
binary = "#bd93f9"  # Binary: light purple
float = "#bd93f9"  # Float: light purple
hex = "#bd93f9"  # Hex: light purple
integer = "#bd93f9"  # Integer: light purple
long = "#bd93f9"  # Long: light purple
octal = "#bd93f9"  # Octal: light purple

# Comment colors
[comment]
hashbang = "#6272a4"  # Hashbang: blue-gray
multiline = "#6272a4"  # Multiline: blue-gray
preproc = "#ff79c6"  # Preproc: pink
preprocfile = "#f1fa8c"  # Preprocfile: yellow
single = "#6272a4"  # Single: blue-gray
special = "#6272a4"  # Special: blue-gray
